/** 进化形态：原核 → 真核单细胞 → 多细胞 → 复杂多细胞 → 病毒聚合体 */
export const EVOLUTIONS = [
  {
    id: 0,
    name: "原核细胞",
    radius: 16,
    segmentCount: 3,
    nuclei: 1,
    color: "#3ecfb0",
    coreColor: "#9be8d6",
    pointsToEvolve: 12,
    complexity: 1,
  },
  {
    id: 1,
    name: "真核单细胞",
    radius: 24,
    segmentCount: 5,
    nuclei: 1,
    color: "#5ec4c8",
    coreColor: "#b8f0ef",
    pointsToEvolve: 28,
    complexity: 2,
  },
  {
    id: 2,
    name: "原始多细胞",
    radius: 34,
    segmentCount: 8,
    nuclei: 1,
    color: "#e8c27a",
    coreColor: "#ffe6a8",
    pointsToEvolve: 48,
    complexity: 3,
  },
  {
    id: 3,
    name: "复杂多细胞",
    radius: 46,
    segmentCount: 12,
    nuclei: 1,
    color: "#7eb6ff",
    coreColor: "#d4e7ff",
    pointsToEvolve: 72,
    complexity: 4,
  },
  {
    id: 4,
    name: "病毒聚合体",
    radius: 58,
    segmentCount: 16,
    nuclei: 1,
    color: "#e07a6a",
    coreColor: "#ffc4bc",
    pointsToEvolve: Infinity,
    complexity: 5,
  },
];

/** 生物圈层级：进化后可前往下一层 */
export const LAYERS = [
  {
    id: 0,
    name: "原核海域",
    bgTop: "#12505c",
    bgBottom: "#041820",
    accent: "#3ecfb0",
    protein: "#9be8d6",
    dna: "#e8c27a",
    proteinCount: 42,
    dnaCount: 6,
    normalCount: 10,
    requiredEvolution: 0,
    boss: {
      name: "裂殖霸主",
      radius: 52,
      nuclei: 3,
      color: "#c45c5c",
    },
  },
  {
    id: 1,
    name: "单细胞带",
    bgTop: "#0a3540",
    bgBottom: "#020f14",
    accent: "#5ec4c8",
    protein: "#7fd4d8",
    dna: "#f0d7a0",
    proteinCount: 38,
    dnaCount: 7,
    normalCount: 12,
    requiredEvolution: 1,
    boss: {
      name: "纤毛暴君",
      radius: 64,
      nuclei: 4,
      color: "#b85c7a",
    },
  },
  {
    id: 2,
    name: "多细胞礁",
    bgTop: "#061820",
    bgBottom: "#01070a",
    accent: "#e8c27a",
    protein: "#f0d7a0",
    dna: "#7eb6ff",
    proteinCount: 34,
    dnaCount: 8,
    normalCount: 14,
    requiredEvolution: 2,
    boss: {
      name: "群核巨兽",
      radius: 78,
      nuclei: 5,
      color: "#8a6ad1",
    },
  },
  {
    id: 3,
    name: "病毒风暴",
    bgTop: "#040c14",
    bgBottom: "#000408",
    accent: "#7eb6ff",
    protein: "#a8ceff",
    dna: "#e07a6a",
    proteinCount: 30,
    dnaCount: 8,
    normalCount: 16,
    requiredEvolution: 3,
    boss: {
      name: "噬界母体",
      radius: 92,
      nuclei: 6,
      color: "#e07a6a",
    },
  },
];

export const WORLD = {
  width: 2600,
  height: 2600,
};

export const PLAYER = {
  baseSpeed: 105,
  boostSpeed: 195,
  boostDuration: 0.55,
  boostCooldown: 1.35,
  turnRate: 9,
  segmentSpacing: 11,
  nucleusRadiusFactor: 0.34,
  eatRangeBonus: 4,
};
